# Generated by Django 4.0.1 on 2022-02-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_hashtag_user_biography_user_birthday_subscription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtagcontent',
            old_name='name',
            new_name='hashtag',
        ),
    ]
